import type { Intern } from "./types";

export const DEMO_INTERNS: Intern[] = [
  {
    id: "LC-2025-001",
    name: "Saina Khadka",
    email: "saina@example.com",
    photo: "https://avatars.githubusercontent.com/u/149309066?v=4",
    post: "Frontend Developer Intern",
    joiningDate: "Nov 29, 2025",
    endingDate: "",
    linkedin: "https://www.linkedin.com/in/saina-khadka-433296394/",
  },
  {
    id: "LC-2026-002",
    name: "Roshani Shrestha",
    email: "roshani@example.com",
    photo: "https://avatars.githubusercontent.com/u/147016687?v=4",
    post: "Frontend Developer Intern",
    joiningDate: "Jan 04, 2026",
    endingDate: "",
    linkedin: "https://linkedin.com/in/marcusthorne",
  },
  {
    id: "LC-2024-003",
    name: "Elena Rodriguez",
    email: "elena.r@example.com",
    photo: "https://picsum.photos/seed/elena/300/300",
    post: "Backend Engineering Intern",
    joiningDate: "Dec 01, 2023",
    endingDate: "Mar 01, 2024",
    linkedin: "https://linkedin.com/in/elenarodriguez",
  },
  {
    id: "LC-2026-004",
    name: "Nishant Bk",
    email: "nishant@example.com",
    photo: "https://avatars.githubusercontent.com/u/125780674?v=4",
    post: "Frontend Developer Intern",
    joiningDate: "Jan 04, 2026",
    endingDate: "",
    linkedin: "https://www.linkedin.com/in/nishant-bk/",
  },
  {
    id: "LC-2026-005",
    name: "Reshmi Rajchal",
    email: "reshmi@example.com",
    photo:
      "https://media.licdn.com/dms/image/v2/D4D03AQHSkya0ezQUzA/profile-displayphoto-crop_800_800/B4DZhKS7jIGsAQ-/0/1753593137745?e=1769644800&v=beta&t=JqJjznt6-neohLh6V1_e8ARd-grhaQ3E9nMoO75LNJo",
    post: "UI/UX Intern",
    joiningDate: "Jan 06, 2026",
    endingDate: "",
    linkedin: "https://www.linkedin.com/in/reshmi-rajchal/",
  },
];
